### ISSUE TITLE
什么是可暂停，什么渐进式？

### ISSUE THREAD

**Issue by wgy8283335** [lealone/HanSQL#1]
你好前辈，向问一下你的SQL引擎，为什么叫可暂停，渐进式？
这有什么含义吗？

**Comment by codefollower** [comment]
这里有解释
https://weibo.com/1773116334/KoJT3E3jl

**Comment by wgy8283335** [comment]
> 这里有解释
> https://weibo.com/1773116334/KoJT3E3jl

谢谢。 我还有个小疑惑，就是用Java来开发数据库，会面临一个垃圾回收过程中Stop World的问题，会影响事务处理的时间延迟。请问，前辈在这方面如何考量？

**Comment by codefollower** [comment]
gc 的问题请看这个
https://weibo.com/1773116334/KbNKzCrE7
